apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |
    bind 0.0.0.0
    port 6379
    dir /data
    appendonly yes
    cluster-enabled yes
    cluster-config-file /data/nodes.conf
    cluster-node-timeout 5000
