apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-master-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-slave-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
