apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-slave
spec:
  serviceName: "redis"
  replicas: 2
  selector:
    matchLabels:
      app: redis
      role: slave
  template:
    metadata:
      labels:
        app: redis
        role: slave
    spec:
      initContainers:
        - name: wait-for-master
          image: busybox:latest
          command: ["sh", "-c", "until nslookup redis-master-0.redis.default.svc.cluster.local; do echo waiting for redis-master; sleep 2; done"]
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: data
              mountPath: /data
          command: ["redis-server", "--slaveof", "redis-master-0.redis.default.svc.cluster.local", "6379"]
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: redis-slave-pvc
